# Site settings
author: elegant-demo-8526
title: 
header-img: img/home-bg.png
email: leslyj2@gmail.com
copyright_name: elegant-demo-8526
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jlesly

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
