# Site settings
author: Lesly Juarez
title: Lesly Writes
header-img: img/home-bg.png
email: leslyj2@gmail.com
copyright_name: Lesly Juarez
description: > # this means to ignore newlines until "baseurl:"
  My Journey Through Flatiron School's Software Development Course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jlesly

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
